### ISSUE TITLE
referrer_url not propagated

### ISSUE THREAD

**Issue by selapalomo** [stape-io/facebook-tag#55]
Hi,
it is possible that referrer_url attribute is not correctly propagated?
Looks like its looking for serverEventDataList.referrer_url but page_referrer is never retrieved and mapped in referrer_url .
Its working fine for event_source_url 
if (eventData.page_location)
    mappedData.event_source_url = eventData.page_location;

**Comment by Bukashk0zzz** [comment]
Fixed.

**Comment by selapalomo** [comment]
Hi, after update to the last template version referrer is still not propagated, at least, in sGTM debug console is not visible.
Is there any dedicated configuration in the tag to make it work?
